#!/bin/bash
# ./contest [ID]

if [ "$#" -ne 1 ]
then
  echo "USAGE: ./contest [ID]"
  exit 1
fi
ID=$1

TMP=$(dirname "$0")/..
DIR=$(cd "$TMP" || exit 1; pwd)
MRS=$DIR/tool/cmain.rs
RST=$DIR/src/contest/q$ID.rs

# generate .rs if not exists
if [ ! -f "$RST" ]
then
  cp "$DIR"/tool/cskel.rs "$RST"
  cp "$DIR"/src/contest/mod.rs "$DIR"/.mod.rs
  echo "pub mod q$ID;" >> "$DIR"/.mod.rs
  sort "$DIR"/.mod.rs > "$DIR"/src/contest/mod.rs
  rm "$DIR"/.mod.rs
fi

# modify main.rs
sed "s/qA/q$ID/g" "$MRS" > "$DIR"/src/main.rs